#!/usr/bin/env python3

from mailcleaner.db import base
from sqlalchemy import Column, String, BLOB, Boolean
from sqlalchemy.dialects.mysql import INTEGER
from . import BaseModel


class DomainPref(base, BaseModel):
    """
    domain_pref table
    """
    __tablename__ = 'domain_pref'

    id = Column(INTEGER(11), nullable=False, primary_key=True)
    viruswall = Column(Boolean, nullable=False, default=True)
    contentwall = Column(Boolean, nullable=False, default=True)
    spamwall = Column(Boolean, nullable=False, default=True)
    scanners = Column(String(50), nullable=False, default="clamav etrust")
    silent = Column(String(100),
                    nullable=False,
                    default="HTML-IFrame All-Viruses Zip-Password")
    block_bad_tnef = Column(Boolean, nullable=False, default=False)
    block_encrypted = Column(Boolean, nullable=False, default=False)
    block_unencrypted = Column(Boolean, nullable=False, default=False)
    allow_passprotected_archives = Column(Boolean,
                                          nullable=False,
                                          default=False)
    allow_partial = Column(Boolean, nullable=False, default=False)
    allow_external_bodies = Column(Boolean, nullable=False, default=False)
    allow_iframe = Column(Boolean, nullable=False, default=False)
    allow_forms = Column(Boolean, nullable=False, default=True)
    allow_scripts = Column(Boolean, nullable=False, default=False)
    allow_codebase = Column(Boolean, nullable=False, default=False)
    convert_danger_to_text = Column(Boolean, nullable=False, default=False)
    convert_html_to_text = Column(Boolean, nullable=False, default=False)
    notify_sender = Column(Boolean, nullable=False, default=True)
    notify_virus_sender = Column(Boolean, nullable=False, default=False)
    notify_blocked_sender = Column(Boolean, nullable=False, default=True)
    notify_blocked_content = Column(Boolean, nullable=False, default=True)
    virus_modify_subject = Column(Boolean, nullable=False, default=True)
    virus_subject = Column(String(20), nullable=False, default="{Virus?}")
    file_modify_subject = Column(Boolean, nullable=False, default=True)
    file_subject = Column(String(20), nullable=False, default="{Virus?}")
    content_modify_subject = Column(Boolean, nullable=False, default=True)
    content_subject = Column(String(20), nullable=False, default="{Virus?}")
    warning_attach = Column(Boolean, nullable=False, default=True)
    warning_filename = Column(String(50),
                              nullable=False,
                              default="AttentionVirus.txt")
    warning_encoding_charset = Column(String(20),
                                      nullable=False,
                                      default="ISO-8859-1")
    use_bayes = Column(Boolean, nullable=False, default=True)
    bayes_autolearn = Column(Boolean, nullable=False, default=True)
    ok_languages = Column(String(50), nullable=False, default="fr en de it es")
    ok_locales = Column(String(50), nullable=False, default="fr en de it es")
    use_rbls = Column(Boolean, nullable=False, default=True)
    rbls_timeout = Column(INTEGER(11), nullable=False, default=20)
    use_dcc = Column(Boolean, nullable=False, default=True)
    dcc_timeout = Column(INTEGER(11), nullable=False, default=10)
    use_razor = Column(Boolean, nullable=False, default=True)
    razor_timeout = Column(INTEGER(11), nullable=False, default=10)
    use_pyzor = Column(Boolean, nullable=False, default=True)
    pyzor_timeout = Column(INTEGER(11), nullable=False, default=10)
    auth_type = Column(String(10), nullable=False, default="imap")
    auth_param = Column(String(200), nullable=True)
    auth_server = Column(String(100), nullable=False, default="localhost")
    auth_modif = Column(String(100), nullable=False, default="localhost")
    address_fetcher = Column(String(10), nullable=False, default="at_login")
    allow_smtp_auth = Column(Boolean, nullable=False, default=False)
    smtp_auth_cachetime = Column(INTEGER(11), nullable=False, default=86400)
    delivery_type = Column(INTEGER(11), nullable=False, default=1)
    daily_summary = Column(Boolean, nullable=False, default=False)
    weekly_summary = Column(Boolean, nullable=False, default=True)
    monthly_summary = Column(Boolean, nullable=False, default=False)
    summary = Column(Boolean, nullable=False, default=True)
    summary_freq = Column(INTEGER(11), nullable=False, default=1)
    summary_to = Column(String(200), nullable=True)
    spam_tag = Column(String(20), nullable=False, default="{Spam?}")
    quarantine_bounces = Column(Boolean, nullable=False, default=False)
    language = Column(String(10), nullable=False)
    gui_displayed_spams = Column(INTEGER(11), nullable=False, default=20)
    gui_displayed_days = Column(INTEGER(11), nullable=False, default=7)
    gui_mask_forced = Column(Boolean, nullable=False, default=False)
    gui_default_address = Column(String(200), nullable=True)
    gui_graph_type = Column(String(20), nullable=False, default="bar")
    gui_group_quarantines = Column(Boolean, nullable=False, default=False)
    web_template = Column(String(50), nullable=False, default="default")
    summary_template = Column(String(50), nullable=False, default="default")
    summary_type = Column(String(20), nullable=False, default="html")
    report_template = Column(String(50), nullable=False, default="default")
    support_email = Column(String(50), nullable=True)
    systemsender = Column(String(250), nullable=True)
    falseneg_to = Column(String(250), nullable=True)
    falsepos_to = Column(String(250), nullable=True)
    supportemail = Column(String(250), nullable=True)
    supportname = Column(String(250), nullable=True)
    presharedkey = Column(String(100), nullable=True)
    enable_whitelists = Column(Boolean, nullable=False, default=False)
    enable_warnlists = Column(Boolean, nullable=False, default=False)
    enable_blacklists = Column(Boolean, nullable=False, default=False)
    notice_wwlists_hit = Column(Boolean, nullable=False, default=False)
    warnhit_template = Column(String(50), nullable=False, default="default")
    ldapcallout = Column(INTEGER(11), nullable=True)
    ldapcalloutserver = Column(String(200), nullable=True)
    ldapcalloutparam = Column(String(200), nullable=True)
    extcallout_type = Column(String(200), nullable=True)
    extcallout_param = Column(BLOB, nullable=True)
    addlist_posters = Column(BLOB, nullable=True)
    archive_mail = Column(Boolean, nullable=False, default=False)
    archive_spam = Column(Boolean, nullable=False, default=False)
    copyto_mail = Column(String(250), nullable=True)
    acc_max_daily_users = Column(INTEGER(11), nullable=False, default=0)
    batv_check = Column(Boolean, nullable=False, default=False)
    batv_secret = Column(String(200), nullable=True)
    prevent_spoof = Column(Boolean, nullable=False, default=False)
    dkim_domain = Column(String(255), nullable=True)
    dkim_selector = Column(String(255), nullable=True)
    dkim_pkey = Column(BLOB, nullable=True)
    require_incoming_tls = Column(Boolean, nullable=False, default=False)
    require_outgoing_tls = Column(Boolean, nullable=False, default=False)
    allow_newsletters = Column(Boolean, nullable=False, default=True)
